import { Stock, Trade, Portfolio } from './types';

export const mockStocks: Stock[] = [
  {
    ticker: 'OKEA.OL',
    name: 'OKEA ASA',
    price: 32.50,
    change: 0.78,
    changePercent: 2.4,
    kScore: 84,
    rsi: 68.5,
    signal: 'BUY',
    target: 39.00,
    stopLoss: 31.35,
    gainKr: 6.50,
    gainPercent: 20.0,
    riskKr: 1.15,
    riskPercent: 3.5,
    timeHorizon: '2-6 uker',
    market: 'OSLO',
    strategies: ['MOMENTUM'],
  },
  {
    ticker: 'VAR.OL',
    name: 'Vår Energi',
    price: 36.80,
    change: 0.44,
    changePercent: 1.2,
    kScore: 82,
    rsi: 72.4,
    signal: 'BUY',
    target: 42.32,
    stopLoss: 35.52,
    gainKr: 5.52,
    gainPercent: 15.0,
    riskKr: 1.28,
    riskPercent: 3.5,
    timeHorizon: '3-8 uker',
    market: 'OSLO',
    strategies: ['MOMENTUM'],
  },
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    price: 178.25,
    change: 2.15,
    changePercent: 1.22,
    kScore: 79,
    rsi: 65.2,
    signal: 'BUY',
    target: 195.00,
    stopLoss: 170.00,
    gainKr: 16.75,
    gainPercent: 9.4,
    riskKr: 8.25,
    riskPercent: 4.6,
    timeHorizon: '4-8 uker',
    market: 'USA',
    strategies: ['MOMENTUM', 'BUFFETT'],
  },
  {
    ticker: 'SALM.OL',
    name: 'SalMar ASA',
    price: 524.00,
    change: -2.50,
    changePercent: -0.48,
    kScore: 76,
    rsi: 58.3,
    signal: 'HOLD',
    target: 580.00,
    stopLoss: 505.00,
    gainKr: 56.00,
    gainPercent: 10.7,
    riskKr: 19.00,
    riskPercent: 3.6,
    timeHorizon: '4-10 uker',
    market: 'OSLO',
    strategies: ['BUFFETT'],
  },
  {
    ticker: 'MOWI.OL',
    name: 'Mowi ASA',
    price: 195.50,
    change: 1.20,
    changePercent: 0.62,
    kScore: 74,
    rsi: 62.1,
    signal: 'HOLD',
    target: 215.00,
    stopLoss: 187.00,
    gainKr: 19.50,
    gainPercent: 10.0,
    riskKr: 8.50,
    riskPercent: 4.3,
    timeHorizon: '3-8 uker',
    market: 'OSLO',
    strategies: ['MOMENTUM', 'BUFFETT'],
  },
  {
    ticker: 'EQNR.OL',
    name: 'Equinor ASA',
    price: 265.80,
    change: 3.20,
    changePercent: 1.22,
    kScore: 71,
    rsi: 55.8,
    signal: 'HOLD',
    target: 290.00,
    stopLoss: 255.00,
    gainKr: 24.20,
    gainPercent: 9.1,
    riskKr: 10.80,
    riskPercent: 4.1,
    timeHorizon: '4-8 uker',
    market: 'OSLO',
    strategies: ['BUFFETT', 'TVEITEREID'],
  },
  {
    ticker: 'DNB.OL',
    name: 'DNB Bank ASA',
    price: 198.40,
    change: 0.80,
    changePercent: 0.41,
    kScore: 68,
    rsi: 51.4,
    signal: 'HOLD',
    target: 215.00,
    stopLoss: 192.00,
    gainKr: 16.60,
    gainPercent: 8.4,
    riskKr: 6.40,
    riskPercent: 3.2,
    timeHorizon: '3-6 uker',
    market: 'OSLO',
    strategies: ['BUFFETT'],
  },
  {
    ticker: 'NEL.OL',
    name: 'Nel ASA',
    price: 4.85,
    change: -0.15,
    changePercent: -3.0,
    kScore: 45,
    rsi: 78.9,
    signal: 'SELL',
    target: 5.50,
    stopLoss: 4.50,
    gainKr: 0.65,
    gainPercent: 13.4,
    riskKr: 0.35,
    riskPercent: 7.2,
    timeHorizon: '2-6 uker',
    market: 'OSLO',
    strategies: ['MOMENTUM'],
  },
];

export const mockTrades: Trade[] = [
  {
    id: '1',
    ticker: 'OKEA.OL',
    entryPrice: 32.50,
    quantity: 100,
    entryDate: new Date('2024-01-15'),
    portfolioId: 'portfolio-1',
    stopLoss: 29.50,
    target: 38.50,
    timeHorizonEnd: new Date('2024-03-01'),
    status: 'ACTIVE',
    deadMoneyWarning: false,
  },
  {
    id: '2',
    ticker: 'VAR.OL',
    entryPrice: 36.80,
    quantity: 150,
    entryDate: new Date('2024-01-10'),
    portfolioId: 'portfolio-1',
    stopLoss: 33.50,
    target: 42.00,
    timeHorizonEnd: new Date('2024-02-28'),
    status: 'ACTIVE',
    deadMoneyWarning: false,
  },
];

export const mockPortfolios: Portfolio[] = [
  {
    id: 'portfolio-1',
    name: 'K-Momentum Portfolio',
    strategyBucket: 'K-Momentum',
    trades: mockTrades,
  },
  {
    id: 'portfolio-2',
    name: 'Legacy Portfolio',
    strategyBucket: 'Legacy',
    trades: [],
  },
];
