import { Stock, Trade, Portfolio } from './types';

export const mockStocks: Stock[] = [
  {
    ticker: 'OKEA.OL',
    name: 'OKEA ASA',
    price: 32.50,
    change: 0.75,
    changePercent: 2.36,
    kScore: 84,
    signal: 'BUY',
    target: 38.50,
    stopLoss: 29.50,
    gainKr: 6.00,
    gainPercent: 18.46,
    riskKr: 3.00,
    riskPercent: 9.23,
    timeHorizon: '3-6 uker',
    market: 'OSLO',
    strategies: ['MOMENTUM'],
  },
  {
    ticker: 'VAR.OL',
    name: 'Var Energi ASA',
    price: 36.80,
    change: 0.45,
    changePercent: 1.24,
    kScore: 82,
    signal: 'BUY',
    target: 42.00,
    stopLoss: 33.50,
    gainKr: 5.20,
    gainPercent: 14.13,
    riskKr: 3.30,
    riskPercent: 8.97,
    timeHorizon: '3-6 uker',
    market: 'OSLO',
    strategies: ['MOMENTUM'],
  },
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    price: 175.50,
    change: 2.30,
    changePercent: 1.33,
    kScore: 78,
    signal: 'BUY',
    target: 195.00,
    stopLoss: 165.00,
    gainKr: 19.50,
    gainPercent: 11.11,
    riskKr: 10.50,
    riskPercent: 5.98,
    timeHorizon: '4-8 uker',
    market: 'USA',
    strategies: ['MOMENTUM', 'BUFFETT'],
  },
];

export const mockTrades: Trade[] = [
  {
    id: '1',
    ticker: 'OKEA.OL',
    entryPrice: 32.50,
    quantity: 100,
    entryDate: new Date('2024-01-15'),
    portfolioId: 'portfolio-1',
    stopLoss: 29.50,
    target: 38.50,
    timeHorizonEnd: new Date('2024-03-01'),
    status: 'ACTIVE',
    deadMoneyWarning: false,
  },
  {
    id: '2',
    ticker: 'VAR.OL',
    entryPrice: 36.80,
    quantity: 150,
    entryDate: new Date('2024-01-10'),
    portfolioId: 'portfolio-1',
    stopLoss: 33.50,
    target: 42.00,
    timeHorizonEnd: new Date('2024-02-28'),
    status: 'ACTIVE',
    deadMoneyWarning: false,
  },
];

export const mockPortfolios: Portfolio[] = [
  {
    id: 'portfolio-1',
    name: 'K-Momentum Portfolio',
    strategyBucket: 'K-Momentum',
    trades: mockTrades,
  },
  {
    id: 'portfolio-2',
    name: 'Legacy Portfolio',
    strategyBucket: 'Legacy',
    trades: [],
  },
];
